apiVersion: v1
kind: Service
metadata:
  name: fastapi-observability
spec:
  selector:
    app: fastapi-observability
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: LoadBalancer
