apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-chart.fullname" . }}
spec:
  selector:
    app: {{ include "myapp-chart.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}